// src/components/NavBar.vue
<template>
  <header class="nav">
    <div class="container">
      <div class="nav-left">
        <a class="nav-item"
          v-scroll-to="'#hero'">
          <span class="logo-text">{{ logo }}</span>
        </a>
      </div>
      <span class="nav-toggle"
        :class="{'is-active' : isExpanded }"
        @click="isExpanded = !isExpanded">
        <span></span>
        <span></span>
        <span></span>
      </span>
      <div class="nav-right nav-menu"
        :class="{ 'is-active': isExpanded }">
        <a v-for="item in menuItems"
          v-bind:key=item.id
          class="nav-item"
          @click.prevent="goTo(item)">
          {{ item.title }}
        </a>
      </div>
    </div>
  </header>
</template>

<script>
export default {
  name: 'navbar',
  data() {
    return {
      logo: 'Shingo Watanabe',
      isExpanded: false,
      menuItems: [
        {
          title: 'AboutMe',
          el: '#about',
        },
        {
          title: 'Skills',
          el: '#skills',
        },
        {
          title: 'Publications',
          el: '#publications',
        },
        // {
        //   title: 'Experiences',
        //   el: '#experiences',
        // },
        {
          title: 'Carrier',
          el: '#carrier',
        },
        {
          title: 'Grants',
          el: '#grants'
        },
        {
          title: 'Products',
          el: '#products',
        },
        {
          title: 'Contact',
          el: '#contact',
        },
      ],
    };
  },
  methods: {
    goTo(item) {
      this.isExpanded = false;
      if (item.url) {
        window.location.assign(item.url);
      } else {
        this.$scrollTo(item.el);
      }
    },
  },
};
</script>

<style lang="scss" scoped>
  .logo-text {
    text-transform: uppercase;
  }
</style>

// src/components/layout/NavBar.tsx
import React, { useState } from 'react';
import { MenuItem } from '../../types';
import { useSmoothScroll } from '../../hooks';
import './NavBar.scss';

const NavBar: React.FC = () => {
  const [isExpanded, setIsExpanded] = useState(false);
  const logo = 'Shingo Watanabe';

  const menuItems: MenuItem[] = [
    {
      title: 'AboutMe',
      el: '#about',
    },
    {
      title: 'Skills',
      el: '#skills',
    },
    {
      title: 'Publications',
      el: '#publications',
    },
    {
      title: 'Carrier',
      el: '#carrier',
    },
    {
      title: 'Grants',
      el: '#grants'
    },
    {
      title: 'Products',
      el: '#products',
    },
    {
      title: 'Contact',
      el: '#contact',
    },
  ];

  const { scrollToElement } = useSmoothScroll();

  const goTo = (item: MenuItem) => {
    setIsExpanded(false);
    scrollToElement(item.el);
  };

  const scrollToHero = () => {
    scrollToElement('#hero');
  };

  return (
    <nav className="navbar" role="navigation" aria-label="main navigation">
      <div className="container">
        <div className="navbar-brand">
          <button className="navbar-item logo-item" onClick={scrollToHero}>
            <span className="logo-text">{logo}</span>
          </button>

          <button
            className={`navbar-burger ${isExpanded ? 'is-active' : ''}`}
            aria-label="menu"
            aria-expanded={isExpanded}
            onClick={() => setIsExpanded(!isExpanded)}
          >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </button>
        </div>

        <div className={`navbar-menu ${isExpanded ? 'is-active' : ''}`}>
          <div className="navbar-end">
            {menuItems.map((item, index) => (
              <button
                key={index}
                className="navbar-item nav-link"
                onClick={() => goTo(item)}
              >
                {item.title}
              </button>
            ))}
          </div>
        </div>
      </div>
    </nav>
  );
};

export default NavBar;
