// src/components/Skills/index.vue
<template>
  <section id="skills" class="section">
    <div class="container">
      <div class="block has-text-centered">
        <h2 class="title is-2">Skills</h2>
        <separator></separator>
        <h5 class="subtitle is-5">Technologies I have used.</h5>
      </div>
      <div class="skills columns is-multiline is-mobile">
        <div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop"
          v-for="(skill, index) in skills"
          :key="index">
          <div class="skill">
            <a class="image"
              target="_blank"
              rel="noopener"
              :href="skill.url"
              :title="skill.name">
              <clazy-load :src="skill.image">
                <div v-html="skill.image" />
                <div class="preloader" slot="placeholder" />
              </clazy-load>

            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { VueClazyLoad } from 'vue-clazy-load'

import skills from './skills';

export default {
  name: 'skills',
  data() {
    return {
      skills,
    };
  },
  mounted() {
    sr.reveal('.skill', 50);
  },
  components: {
    VueClazyLoad,
  },
};
</script>

<style lang="scss" scoped>
  @import '~vars';

  .skills {
    max-width: $desktop;
    margin: auto;
  }

  .columns {
    justify-content: center;
  }

  .skill {
    padding: 0.5em;
    margin: 0 auto;
    // max-width: 50%;
    // opacity: 0.8;
    transition: all 0.15s ease-in;
    width: 100px;

    &:hover {
      opacity: 1;
      transform: scale(1.1);
      cursor: pointer
    }
  }
</style>

// src/components/sections/Skills.tsx
import React, { useEffect } from 'react';
import { Separator } from '../common';
import { skills } from '../../data/skills';
import './Skills.scss';

const Skills: React.FC = () => {
  useEffect(() => {
    const skillElements = document.querySelectorAll('.skill');
    skillElements.forEach((el, index) => {
      (el as HTMLElement).style.animation = `fadeInUp 1s ease ${index * 0.05}s both`;
    });
  }, []);

  return (
    <section id="skills" className="section">
      <div className="container">
        <div className="block has-text-centered">
          <h2 className="title is-2">Skills</h2>
          <Separator />
          <h5 className="subtitle is-5">Technologies I have used.</h5>
        </div>
        <div className="skills columns is-multiline is-mobile">
          {skills.map((skill, index) => (
            <div
              key={index}
              className="column is-half-mobile is-one-third-tablet is-one-quarter-desktop"
            >
              <div className="skill">
                <div className="image" title={skill.name}>
                  <img src={skill.image} alt={skill.name} />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Skills;
